// ─── Agent OS — Default Skill Definitions ─────────────────────
// 40+ default skills for the Skill Registry.
// These are seeded into the database via SkillRegistryService.seedDefaults().
//
// Categories: analysis, creation, communication, automation,
//             management, technical, media, specialized

export interface DefaultSkillDefinition {
  key: string;
  name: string;
  description: string;
  category: string;
  icon: string;
  version: string;
  status: string;
  requiredTools: string[];
  tags: string[];
}

export const DEFAULT_SKILLS: DefaultSkillDefinition[] = [
  // ═══════════════════════════════════════════════════════════
  // ─── Analysis ────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'research',
    name: 'Research',
    description: 'Conduct structured research on topics using web sources, databases, and internal knowledge. Synthesizes findings into comprehensive reports with citations.',
    category: 'analysis',
    icon: '🔍',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search', 'rag.query'],
    tags: ['research', 'information-gathering', 'web-search'],
  },
  {
    key: 'deep_research',
    name: 'Deep Research',
    description: 'Perform in-depth, multi-source research with iterative exploration. Goes beyond surface-level findings to uncover deeper insights and cross-validate information.',
    category: 'analysis',
    icon: '🔬',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search', 'rag.query', 'browser_ai_provider'],
    tags: ['research', 'deep-analysis', 'multi-source'],
  },
  {
    key: 'web_search',
    name: 'Web Search',
    description: 'Search the web for real-time information, news, and data. Handles query formulation, result filtering, and relevance ranking.',
    category: 'analysis',
    icon: '🌐',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search'],
    tags: ['search', 'web', 'real-time'],
  },
  {
    key: 'fact_checking',
    name: 'Fact Checking',
    description: 'Verify claims and statements against reliable sources. Cross-references multiple data points to assess accuracy and identify misinformation.',
    category: 'analysis',
    icon: '✅',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search'],
    tags: ['verification', 'accuracy', 'fact-check'],
  },
  {
    key: 'data_analysis',
    name: 'Data Analysis',
    description: 'Analyze structured and unstructured data to extract insights, identify patterns, and generate statistical summaries. Supports CSV, JSON, and database sources.',
    category: 'analysis',
    icon: '📊',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['database.query', 'filesystem.read'],
    tags: ['data', 'analytics', 'statistics', 'insights'],
  },
  {
    key: 'summarization',
    name: 'Summarization',
    description: 'Condense long documents, conversations, and data into concise, accurate summaries. Preserves key information and context while reducing verbosity.',
    category: 'analysis',
    icon: '📝',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['summarization', 'condensation', 'extraction'],
  },
  {
    key: 'ocr',
    name: 'OCR',
    description: 'Extract text and structured data from images, scanned documents, and PDFs using optical character recognition. Supports multiple languages and formats.',
    category: 'analysis',
    icon: '👁️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['ocr.extract'],
    tags: ['ocr', 'text-extraction', 'image-to-text'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Creation ────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'coding',
    name: 'Coding',
    description: 'Write, review, and modify code across multiple programming languages and frameworks. Follows best practices, design patterns, and project conventions.',
    category: 'creation',
    icon: '💻',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.read', 'filesystem.write', 'terminal.run'],
    tags: ['coding', 'development', 'programming'],
  },
  {
    key: 'debugging',
    name: 'Debugging',
    description: 'Systematically identify, diagnose, and fix bugs in code. Uses logging, stack trace analysis, and step-by-step reasoning to isolate issues.',
    category: 'creation',
    icon: '🐛',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.read', 'terminal.run'],
    tags: ['debugging', 'troubleshooting', 'bug-fixing'],
  },
  {
    key: 'refactoring',
    name: 'Refactoring',
    description: 'Restructure existing code to improve readability, maintainability, and performance without changing external behavior. Applies design patterns and clean code principles.',
    category: 'creation',
    icon: '🔧',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.read', 'filesystem.write'],
    tags: ['refactoring', 'code-quality', 'clean-code'],
  },
  {
    key: 'architecture_design',
    name: 'Architecture Design',
    description: 'Design software architecture including system structure, component relationships, data flow, and technology choices. Creates architecture diagrams and documentation.',
    category: 'creation',
    icon: '🏛️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.write', 'document.parse'],
    tags: ['architecture', 'design', 'system-design'],
  },
  {
    key: 'database_design',
    name: 'Database Design',
    description: 'Design database schemas, relationships, indexes, and queries. Supports relational and NoSQL databases with normalization and optimization.',
    category: 'creation',
    icon: '🗄️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['database.query'],
    tags: ['database', 'schema', 'data-modeling'],
  },
  {
    key: 'ui_design',
    name: 'UI Design',
    description: 'Create user interface designs, component layouts, and visual specifications. Focuses on aesthetics, consistency, and design system adherence.',
    category: 'creation',
    icon: '🎨',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.write'],
    tags: ['ui', 'design', 'visual', 'interface'],
  },
  {
    key: 'ux_design',
    name: 'UX Design',
    description: 'Design user experiences including user flows, wireframes, interaction patterns, and usability considerations. Prioritizes user needs and accessibility.',
    category: 'creation',
    icon: '🧑‍🎨',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.write'],
    tags: ['ux', 'design', 'usability', 'accessibility'],
  },
  {
    key: 'content_creation',
    name: 'Content Creation',
    description: 'Create written content including articles, documentation, blog posts, marketing copy, and technical writing. Adapts tone and style to target audience.',
    category: 'creation',
    icon: '✍️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.write'],
    tags: ['content', 'writing', 'documentation', 'copywriting'],
  },
  {
    key: 'image_generation',
    name: 'Image Generation',
    description: 'Generate images from text descriptions using AI models. Supports various styles, sizes, and artistic directions for visual content creation.',
    category: 'creation',
    icon: '🖼️',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['image', 'generation', 'ai-art', 'visual'],
  },
  {
    key: 'video_generation',
    name: 'Video Generation',
    description: 'Generate video content from descriptions or scripts. Supports various formats, durations, and styles for dynamic visual content.',
    category: 'creation',
    icon: '🎬',
    version: '1.0.0',
    status: 'experimental',
    requiredTools: [],
    tags: ['video', 'generation', 'multimedia'],
  },
  {
    key: 'voice_generation',
    name: 'Voice Generation',
    description: 'Generate speech and audio content from text using text-to-speech technology. Supports multiple voices, languages, and speaking styles.',
    category: 'creation',
    icon: '🎙️',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['voice', 'tts', 'speech', 'audio'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Communication ──────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'translation',
    name: 'Translation',
    description: 'Translate text between languages with contextual accuracy. Handles idioms, technical terminology, and cultural nuances for natural-sounding output.',
    category: 'communication',
    icon: '🌍',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['translation.translate'],
    tags: ['translation', 'language', 'localization'],
  },
  {
    key: 'email_management',
    name: 'Email Management',
    description: 'Draft, review, categorize, and manage email communications. Handles templates, follow-ups, priority sorting, and response suggestions.',
    category: 'communication',
    icon: '📧',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['notification.send'],
    tags: ['email', 'communication', 'correspondence'],
  },
  {
    key: 'social_media_management',
    name: 'Social Media Management',
    description: 'Create, schedule, and manage social media content across platforms. Handles audience engagement, trend analysis, and content calendars.',
    category: 'communication',
    icon: '📱',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search', 'notification.send'],
    tags: ['social-media', 'content', 'scheduling'],
  },
  {
    key: 'marketing',
    name: 'Marketing',
    description: 'Develop marketing strategies, campaigns, and content. Includes audience segmentation, channel planning, A/B testing concepts, and performance analysis.',
    category: 'communication',
    icon: '📣',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search'],
    tags: ['marketing', 'campaigns', 'strategy'],
  },
  {
    key: 'sales',
    name: 'Sales',
    description: 'Support sales processes including lead outreach, proposal drafting, objection handling, and pipeline management. Generates personalized communications.',
    category: 'communication',
    icon: '🤝',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['notification.send'],
    tags: ['sales', 'outreach', 'proposals'],
  },
  {
    key: 'seo',
    name: 'SEO',
    description: 'Optimize content and websites for search engines. Includes keyword research, on-page optimization, meta descriptions, and content strategy for ranking.',
    category: 'communication',
    icon: '🔎',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser.search'],
    tags: ['seo', 'optimization', 'keywords', 'ranking'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Automation ──────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'browser_automation',
    name: 'Browser Automation',
    description: 'Automate browser interactions including navigation, form filling, data extraction, and multi-step workflows. Supports headless and interactive modes.',
    category: 'automation',
    icon: '🤖',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['browser_ai_provider', 'browser.search'],
    tags: ['browser', 'automation', 'scraping', 'web'],
  },
  {
    key: 'computer_use',
    name: 'Computer Use',
    description: 'Interact with computer desktop environments — open applications, manage files, execute commands, and operate GUI-based tools autonomously.',
    category: 'automation',
    icon: '🖥️',
    version: '1.0.0',
    status: 'experimental',
    requiredTools: ['terminal.run', 'filesystem.read', 'filesystem.write'],
    tags: ['computer', 'desktop', 'gui', 'automation'],
  },
  {
    key: 'automation',
    name: 'Automation',
    description: 'Design and execute automated workflows, triggers, and scheduled tasks. Integrates with various tools and services for end-to-end process automation.',
    category: 'automation',
    icon: '⚙️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['terminal.run'],
    tags: ['automation', 'workflows', 'triggers'],
  },
  {
    key: 'agent_creation',
    name: 'Agent Creation',
    description: 'Create and configure new agents with appropriate skills, tools, and model settings. Handles agent lifecycle from definition to deployment.',
    category: 'automation',
    icon: '🧬',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['agent', 'creation', 'configuration'],
  },
  {
    key: 'agent_training',
    name: 'Agent Training',
    description: 'Train and fine-tune agent behavior through examples, feedback, and iterative improvement. Adjusts prompts, skills, and configurations for better performance.',
    category: 'automation',
    icon: '🎓',
    version: '1.0.0',
    status: 'beta',
    requiredTools: [],
    tags: ['training', 'fine-tuning', 'agent-improvement'],
  },
  {
    key: 'task_delegation',
    name: 'Task Delegation',
    description: 'Break down complex tasks and delegate sub-tasks to appropriate agents. Manages dependencies, priorities, and tracks delegation outcomes.',
    category: 'automation',
    icon: '📋',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['delegation', 'task-management', 'orchestration'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Management ──────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'project_management',
    name: 'Project Management',
    description: 'Manage project timelines, milestones, resources, and deliverables. Tracks progress, identifies risks, and coordinates team activities.',
    category: 'management',
    icon: '📐',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['project', 'management', 'planning', 'coordination'],
  },
  {
    key: 'lead_qualification',
    name: 'Lead Qualification',
    description: 'Qualify and score leads based on criteria such as fit, engagement, and intent. Automates lead scoring workflows and provides recommendations.',
    category: 'management',
    icon: '🎯',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['database.query'],
    tags: ['leads', 'qualification', 'scoring', 'crm'],
  },
  {
    key: 'crm_management',
    name: 'CRM Management',
    description: 'Manage customer relationship data including contacts, deals, activities, and pipelines. Integrates with CRM tools for data sync and reporting.',
    category: 'management',
    icon: '👥',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['database.query', 'notification.send'],
    tags: ['crm', 'customers', 'relationships', 'pipeline'],
  },
  {
    key: 'calendar_management',
    name: 'Calendar Management',
    description: 'Manage schedules, appointments, and deadlines. Handles meeting coordination, conflict resolution, and time zone awareness.',
    category: 'management',
    icon: '📅',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['notification.send'],
    tags: ['calendar', 'scheduling', 'appointments'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Technical ───────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'legal_analysis',
    name: 'Legal Analysis',
    description: 'Analyze legal documents, regulations, and case law. Identifies relevant provisions, risks, and compliance requirements. Not a substitute for legal counsel.',
    category: 'technical',
    icon: '⚖️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['document.parse', 'rag.query'],
    tags: ['legal', 'analysis', 'compliance', 'regulations'],
  },
  {
    key: 'legal_drafting',
    name: 'Legal Drafting',
    description: 'Draft legal documents, contracts, and agreements using standard templates and clauses. Ensures proper structure, language, and clause coverage.',
    category: 'technical',
    icon: '📜',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.write', 'document.parse'],
    tags: ['legal', 'drafting', 'contracts', 'documents'],
  },
  {
    key: 'contract_review',
    name: 'Contract Review',
    description: 'Review contracts and agreements for risks, ambiguities, and non-standard clauses. Highlights areas requiring attention and suggests improvements.',
    category: 'technical',
    icon: '📑',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['document.parse', 'rag.query'],
    tags: ['contract', 'review', 'risk', 'compliance'],
  },
  {
    key: 'rag_search',
    name: 'RAG Search',
    description: 'Perform retrieval-augmented generation searches across indexed documents. Combines semantic search with LLM generation for contextually relevant answers.',
    category: 'technical',
    icon: '🔎',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['rag.query', 'rag.index'],
    tags: ['rag', 'search', 'retrieval', 'semantic'],
  },
  {
    key: 'embedding_management',
    name: 'Embedding Management',
    description: 'Manage vector embeddings for documents and content. Handles embedding generation, storage, indexing, and similarity search operations.',
    category: 'technical',
    icon: '🧮',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['rag.index'],
    tags: ['embeddings', 'vectors', 'indexing'],
  },
  {
    key: 'document_processing',
    name: 'Document Processing',
    description: 'Process, parse, and transform documents across formats (PDF, DOCX, HTML, Markdown). Extracts structured data and maintains format fidelity.',
    category: 'technical',
    icon: '📄',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['document.parse', 'filesystem.read', 'filesystem.write'],
    tags: ['documents', 'processing', 'parsing', 'transformation'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Media ───────────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'image_editing',
    name: 'Image Editing',
    description: 'Edit and modify images including resizing, cropping, color correction, compositing, and AI-powered edits. Supports common image formats.',
    category: 'media',
    icon: '🖼️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.read', 'filesystem.write'],
    tags: ['image', 'editing', 'visual', 'processing'],
  },
  {
    key: 'video_editing',
    name: 'Video Editing',
    description: 'Edit and process video content including trimming, merging, transitions, subtitles, and format conversion. Supports common video formats.',
    category: 'media',
    icon: '🎥',
    version: '1.0.0',
    status: 'beta',
    requiredTools: ['filesystem.read', 'filesystem.write', 'terminal.run'],
    tags: ['video', 'editing', 'multimedia', 'processing'],
  },
  {
    key: 'audio_processing',
    name: 'Audio Processing',
    description: 'Process and manipulate audio including transcription, noise reduction, format conversion, and speech analysis. Supports common audio formats.',
    category: 'media',
    icon: '🎵',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.read', 'filesystem.write'],
    tags: ['audio', 'processing', 'transcription', 'sound'],
  },

  // ═══════════════════════════════════════════════════════════
  // ─── Specialized ─────────────────────────────────────────
  // ═══════════════════════════════════════════════════════════
  {
    key: 'prompt_engineering',
    name: 'Prompt Engineering',
    description: 'Design, optimize, and test prompts for AI models. Applies prompt patterns, few-shot examples, chain-of-thought, and systematic prompt improvement techniques.',
    category: 'specialized',
    icon: '💡',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['prompt', 'engineering', 'optimization', 'ai'],
  },
  {
    key: 'security_audit',
    name: 'Security Audit',
    description: 'Conduct security audits of code, infrastructure, and configurations. Identifies vulnerabilities, misconfigurations, and compliance gaps with remediation guidance.',
    category: 'specialized',
    icon: '🔒',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['filesystem.read', 'terminal.run', 'git.status'],
    tags: ['security', 'audit', 'vulnerability', 'compliance'],
  },
  {
    key: 'compliance_check',
    name: 'Compliance Check',
    description: 'Verify compliance with regulations, standards, and organizational policies. Checks against GDPR, SOC2, HIPAA, and custom policy frameworks.',
    category: 'specialized',
    icon: '🛡️',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['document.parse', 'rag.query'],
    tags: ['compliance', 'regulations', 'audit', 'policy'],
  },
  {
    key: 'financial_analysis',
    name: 'Financial Analysis',
    description: 'Analyze financial data, generate reports, and provide insights on budgets, forecasts, and financial performance. Supports spreadsheet data and financial statements.',
    category: 'specialized',
    icon: '💰',
    version: '1.0.0',
    status: 'available',
    requiredTools: ['database.query', 'filesystem.read'],
    tags: ['finance', 'analysis', 'budgeting', 'reporting'],
  },
  {
    key: 'communication',
    name: 'Communication',
    description: 'Draft, send, and manage professional communications across channels (chat, email, DM). Handles tone adaptation, escalation, and response drafting.',
    category: 'communication',
    icon: '💬',
    version: '1.0.0',
    status: 'available',
    requiredTools: [],
    tags: ['communication', 'messaging', 'response', 'drafting'],
  },
];
